// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240912135640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            ProductName = "Iphone14",
                            ProductPrice = 60000m
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            ProductName = "Iphone15",
                            ProductPrice = 70000m
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            ProductName = "Iphone16",
                            ProductPrice = 80000m
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            ProductName = "Iphone17",
                            ProductPrice = 90000m
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            ProductName = "Iphone18",
                            ProductPrice = 95000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
